#pragma once
#include <vector>

#include "CardEntity.h"

// struct ProductState {
//   string genre;           // RPG, Adventure, Strategy, ...
//   string platform;        // PC, Console, Mobile
//   string targetAudience;  // Kids, Teens, Adults
//   string artStyle;        // Pixel Art, 3D, Hand-drawn
//   string type;            // Single-player, Multiplayer, MMO, turn-based
// };

// Thoughts:
// - each card can take the state object in and return an updated version
// - each card function is added as a reference to a vector
// - state is generated by taking the starting state then applying each card in
// sequence
// - each time a card is added we recalculate then cache the current state for
// rendering

class GameState {
  std::vector<class CardEntity*> selectedCards = {};
  int complexity = 10;
  int time = 10;
  int price = 10;
  int appeal = 1;
  int quality = 1;
  int progress = 0;

 public:
  GameState() {}
  ~GameState() {
    for (CardEntity* card : selectedCards) {
      delete card;
    }
    selectedCards.clear();
  }
  void addCard(CardEntity* card) { selectedCards.push_back(card); }
};